version: '3'
services:
  hb-back:
    build: .
    ports:
      - "8001:3000"
    volumes:
     - ./:/home/node/app:rw

  postgres:
    image: postgis/postgis:13-master
    restart: always
    volumes:
     - ../db:/var/lib/postgresql/data:rw
    environment:
     - POSTGRES_PASSWORD=change_me
